feat: add rust bindings (#1)
* feat: add rust bindings

* feat: add rust bindings

* fix example bug

* add rust check in CI

* refactor ci

* refactor ci

* fix ci

* remove unused code

diff --git a/.github/workflows/check-generate.yml b/.github/workflows/check-generate.yml
--- a/.github/workflows/check-generate.yml
+++ b/.github/workflows/check-generate.yml
@@ -9,8 +9,8 @@ permissions:
   contents: read
 
 jobs:
-  check-make-generate:
-    name: Check make generate
+  check-go-generate:
+    name: Check make generate-go
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -35,13 +35,39 @@ jobs:
       - name: Check buf installation
         run: buf --version
 
-      - name: Run make generate
-        run: make generate
+      - name: Run make generate-go
+        run: make generate-go
 
-      - name: Check if make generate generated changes that should be committed
+      - name: Check if make generate-go generated changes that should be committed
         run: |
           if [ -n "$(git status --porcelain)" ]; then
-            echo "Error: make generate generated changes that should be committed. Please run 'make generate' and commit the changes."
+            echo "Error: make generate-go generated changes that should be committed. Please run 'make generate-go' and commit the changes."
+            git diff
+            git status
+            exit 1
+          fi
+  
+  check-rust-generate:
+    name: Check make generate-rs
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Rust
+        uses: dtolnay/rust-toolchain@1.82.0
+
+      - name: Install Protoc
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y protobuf-compiler
+
+      - name: Run make generate-rs
+        run: make generate-rs
+
+      - name: Check if make generate-rs generated changes that should be committed
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: make generate-rs generated changes that should be committed. Please run 'make generate-rs' and commit the changes."
             git diff
             git status
             exit 1
